name: Materia OS Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive Project
        uses: actions/upload-artifact@v3
        with:
          name: Materia_Source_Package
          path: |
            AndroidManifest.xml
            додаток/
